spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:yeonseong1234}
    #url: ${DB_URL:jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require}
    #username: ${DB_USERNAME:postgres.oelmefqcgjtjcimlwyay}
    #password: ${DB_PASSWORD:1234} # docker 배포 시 환경변수로 주입 필요!! render에서 비번을 넣을듯

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 60000

  sql:
    init:
      mode: never        # data.sql 자동 실행 금지 -> 지금은 필요없을지도,,,?
      encoding: UTF-8

  jpa:
    open-in-view: false
    defer-datasource-initialization: false  # data.sql 안 쓰면 false로
    hibernate:
      ddl-auto: update   # ✔ 테이블 유지하며 변경사항만 업데이트
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
  #port: 8080
