spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.oelmefqcgjtjcimlwyay
    password: 1234

    hikari:  # ✅ Supabase 커넥션 풀 설정
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 60000

  sql:
    init:
      mode: always # ✅ data.sql 항상 실행
      encoding: UTF-8

  jpa:
    open-in-view: false
    defer-datasource-initialization: true # ✅ JPA 테이블 생성 후 data.sql 실행
    hibernate:
      ddl-auto: update  # ⚠️ 초기화용: 기존 테이블 삭제 후 새로 생성
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
